### ISSUE TITLE
add convention clarification for prenasalization

### ISSUE THREAD

**Issue by bambooforest** [phoible/phoible.github.io#14]
which follows strict place matching, e.g.

n̠t̠ʒ instead of ɲdʒ

**Comment by drammock** [comment]
This is already included in the "place matching" section, right? 

> In PHOIBLE, all affricates, **prenasalized stops**, and pre-stopped nasals adhere to strict place-matching.

Am I missing something?

**Comment by bambooforest** [comment]
No, I must have.
